import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import * as React from 'react';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';


export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>GT News</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/GTNEWS.png" />
        </Head>
      
        <main className={styles.main}>
        <div className={styles.meum_bar}>
            <div className={styles.gtnews_logo}>
              <img className={styles.gtnewslogo} src="GTNEWS.png"></img>
            </div>
            <TextField label="Search" color="secondary" focused />
            
        </div>
          <h1 className={styles.title}>
            Welcome to <a href="https://nextjs.org">Next.js!</a>
          </h1>
          <h1 className="title">
            Read{' '}
            <Link href="/news">
            <a>this page!</a>
            </Link>
          </h1>
        </main>
    </div>
  )
}